name: Lint

on:
    push:
        branches:
            - main
        paths:
            - go.mod
            - go.sum
            - "**/*.go"
            - "**/*.gotmpl"
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-go@v5
              with:
                  cache: true

            - name: 🚨 Lint
              run: go vet
